module.exports = {
  badwords: [
    "anal",
    "anus",
    "arse",
    "ass",
    "ballsack",
    "balls",
    "bastard",
    "bitch",
    "biatch",
    "bloody",
    "blowjob",
    "bollock",
    "bollok",
    "boner",
    "boob",
    "bugger",
    "bum",
    "butt",
    "buttplug",
    "clitoris",
    "cock",
    "coon",
    "crap",
    "cunt",
    "damn",
    "dick",
    "dildo",
    "dyke",
    "fag",
    "feck",
    "fellate",
    "fellatio",
    "felching",
    "fuck",
    "fudgepacker",
    "flange",
    "goddamn",
    "hell",
    "homo",
    "jizz",
    "knobend",
    "labia",
    "muff",
    "nigger",
    "nigga",
    "penis",
    "piss",
    "poop",
    "prick",
    "pube",
    "pussy",
    "queer",
    "scrotum",
    "sex",
    "shit",
    "sh1t",
    "slut",
    "smegma",
    "spunk",
    "tit",
    "tosser",
    "turd",
    "twat",
    "vagina",
    "wank",
    "whore",
    "wtf",
    "putain",
    "merde",
    "connard",
    "salope",
    "enculé",
    "bite",
    "couille",
    "nique",
    "pute",
    "connasse",
    "foutre",
    "chatte",
    "branleur",
    "enfoiré",
    "pd",
    "tafiole",
    "tapette",
    "tantouze",
    "gouine",
    "salaud",
    "ordure",
    "nègre",
    "négro",
    "négresse",
    "motherfucker",
    "cocksucker",
    "fucktard",
    "shithead",
    "asshole",
    "douchebag",
    "cumslut",
    "fuckface",
    "dickhead",
    "cuntrag",
    "fils de pute",
    "va te faire enculer",
    "espèce de connard",
    "trou du cul",
    "suce ma bite",
    "grosse pute",
    "sale race",
    "encule ta mère",
    "mange merde",
    "va chier",
    "nique ta race",
    "sale pédé",
    "sale gouine",
    "sale juif",
    "sale arabe",
    "sale noir",
    "faggot",
    "retard",
    "cuck",
    "wanker",
    "skank",
    "twat",
    "prick",
    "slag",
    "minger",
    "piss off",
    "bollocks",
    "bugger off",
    "chav",
    "git",
    "muppet",
    "naff",
    "pillock",
    "plonker",
    "prat",
    "trollop",
    "munter",
    "knob",
    "bellend",
    "nonce",
    "berk",
    "manky",
    "minge",
    "numpty",
    "scrote",
    "tosser",
    "wazzock",
    "schmuck",
    "kike",
    "spic",
    "wetback",
    "beaner",
    "chink",
    "gook",
    "zipperhead",
    "slant-eye",
    "curry muncher",
    "paki",
    "towelhead",
    "camel jockey",
    "sand nigger",
    "jungle bunny",
    "porch monkey",
    "spade",
    "coon",
    "jigaboo",
    "pickaninny",
    "sambo",
    "Uncle Tom",
    "house nigger",
    "oreo",
    "coconut",
    "banana",
    "cholo",
    "gringo",
    "guido",
    "dago",
    "wop",
    "ginzo",
    "polack",
    "mick",
    "paddy",
    "fenian",
    "taig",
    "kraut",
    "hun",
    "jerry",
    "frog",
    "limey",
    "pom",
    "pommy",
    "rosbif",
    "yid",
    "heeb",
    "hymie",
    "sheeny",
    "shylock",
    "christ-killer",
    "kyke",
    "raghead",
    "goat fucker",
    "dune coon",
    "hajji",
    "muzzie",
    "gyppo",
    "gypsy",
    "pikey",
    "tinker",
    "knacker",
    "fenian",
    "taig",
    "teague",
    "mick",
    "paddy",
    "bog trotter",
    "prod",
    "hun",
    "jock",
    "sweaty",
    "teuchter",
    "sheep shagger",
    "taff",
    "boyo",
    "cunt",
    "twat",
    "fanny",
    "minge",
    "gash",
    "snatch",
    "quim",
    "pussy",
    "clit",
    "cock",
    "dick",
    "prick",
    "knob",
    "bellend",
    "balls",
    "bollocks",
    "nuts",
    "gonads",
    "jizz",
    "spunk",
    "cum",
    "jism",
    "spoog",
    "spooge",
    "sperm",
    "semen",
    "bukkake",
    "facial",
    "rimjob",
    "rimming",
    "rusty trombone",
    "cleveland steamer",
    "dirty sanchez",
    "donkey punch",
    "pearl necklace",
    "golden shower",
    "watersports",
    "scat",
    "coprophilia",
    "2 girls 1 cup",
    "blue waffle",
    "goatse",
    "tubgirl",
    "lemon party",
    "meatspin",
    "prolapse",
    "gape",
    "fisting",
    "felching",
    "snowballing",
    "teabagging",
    "queef",
    "squirt",
    "gushing",
    "creampie",
    "gangbang",
    "bukkake",
    "orgy",
    "threesome",
    "foursome",
    "dp",
    "airtight",
    "spit roast",
    "eiffel tower",
    "lucky pierre",
    "dvda",
    "atm",
    "a2m",
    "ass to mouth",
    "ass to ass",
    "atogm",
    "ass to other girls mouth",
    "bdsm",
    "bondage",
    "domination",
    "submission",
    "sadism",
    "masochism",
    "sadomasochism",
    "fetish",
    "kink",
    "pervert",
    "deviant",
    "nympho",
    "slut",
    "whore",
    "hoe",
    "skank",
    "tramp",
    "trollop",
    "slag",
    "sket",
    "jezebel",
    "harlot",
    "strumpet",
    "floozy",
    "tart",
    "hussy",
    "wench",
    "bint",
    "harridan",
    "crone",
    "battleaxe",
    "bitch",
    "cunt",
    "twat",
    "slapper",
    "slattern",
    "trull",
    "drab",
    "quean",
    "bawd",
    "jade",
    "cyprian",
    "courtesan",
    "prostitute",
    "hooker",
    "call girl",
    "escort",
    "working girl",
    "lady of the night",
    "streetwalker",
    "lot lizard",
    "ho",
    "hoe",
    "trick",
    "john",
    "punter",
    "client",
    "pimp",
    "madam",
    "procurer",
    "pander",
    "whoremonger",
    "flesh peddler",
    "brothel",
    "whorehouse",
    "cathouse",
    "bordello",
    "bagnio",
    "bawdy house",
    "house of ill repute",
    "den of iniquity",
    "massage parlor",
    "rub and tug",
    "happy ending",
    "red light district",
    "stroll",
    "track",
    "stroll ho",
    "track ho",
    "lot lizard",
    "streetwalker",
    "crack whore",
    "meth whore",
    "junkie whore",
    "needle freak",
    "smackhead",
    "crackhead",
    "tweaker",
    "meth head",
    "cokehead",
    "dope fiend",
    "pillhead",
    "barb freak",
    "speed freak",
    "acid head",
    "pothead",
    "stoner",
    "burnout",
    "druggie",
    "junkie",
    "addict",
    "user",
    "abuser",
    "dealer",
    "pusher",
    "trafficker",
    "kingpin",
    "drug lord",
    "narco",
    "narc",
    "snitch",
    "rat",
    "stool pigeon",
    "grass",
    "informant",
    "mole",
    "plant",
    "double agent",
    "turncoat",
    "traitor",
    "backstabber",
    "judas",
    "benedict arnold",
    "quisling",
    "collaborator",
    "fifth columnist",
    "enemy of the state",
    "terrorist",
    "extremist",
    "radical",
    "fundamentalist",
    "zealot",
    "fanatic",
    "jihadist",
    "martyr",
    "kamikaze",
    "suicide bomber",
    "guerrilla",
    "insurgent",
    "rebel",
    "revolutionary",
    "anarchist",
    "nihilist",
    "subversive",
    "dissident",
    "agitator",
    "rabble-rouser",
    "shit-stirrer",
    "troublemaker",
    "instigator",
    "provocateur",
    "firebrand",
    "demagogue",
    "rabble-rouser",
    "propagandist",
    "muckraker",
    "yellow journalist",
    "tabloid hack",
    "paparazzo",
    "gossip monger",
    "rumormonger",
    "scandalmonger",
    "muckraker",
    "mud-slinger",
    "character assassin",
    "libeler",
    "slanderer",
    "defamer",
    "calumniator",
    "vilifier",
    "traducer",
    "maligner",
    "detractor",
    "backbiter",
    "mudslinger",
    "shit-talker",
    "trash-talker",
    "hater",
    "troll",
    "flamer",
    "griefer",
    "cyberbully",
    "internet tough guy",
    "keyboard warrior",
    "neckbeard",
    "incel",
    "nice guy",
    "white knight",
    "simp",
    "cuck",
    "beta",
    "soyboy",
    "snowflake",
    "libtard",
    "cuckservative",
    "feminazi",
    "social justice warrior",
    "virtue signaler",
    "politically correct",
    "triggered",
    "safe space",
    "microaggression",
    "mansplaining",
    "manspreading",
    "toxic masculinity",
    "patriarchy",
    "rape culture",
    "victim blaming",
    "slut shaming",
    "body shaming",
    "fat shaming",
    "skinny shaming",
    "ableism",
    "ageism",
    "classism",
    "colorism",
    "lookism",
    "sizeism",
    "speciesism",
    "carnism",
    "anthropocentrism",
    "ethnocentrism",
    "eurocentrism",
    "orientalism",
    "occidentalism",
    "cultural appropriation",
    "whitewashing",
    "blackface",
    "yellowface",
    "redface",
    "brownface",
    "blackfishing",
    "cultural imperialism",
    "neocolonialism",
    "white savior complex",
    "white guilt",
    "white privilege",
    "male privilege",
    "straight privilege",
    "cisgender privilege",
    "able-bodied privilege",
    "neurotypical privilege",
    "thin privilege",
    "pretty privilege",
    "class privilege",
    "educational privilege",
    "linguistic privilege",
    "religious privilege",
    "secular privilege",
    "first world privilege",
    "global north privilege",
    "digital privilege",
    "technological privilege",
    "environmental privilege",
    "green privilege",
    "climate privilege",
    "food privilege",
    "water privilege",
    "housing privilege",
    "transportation privilege",
    "mobility privilege",
    "temporal privilege",
    "generational privilege",
    "age privilege",
    "youth privilege",
    "adult privilege",
    "elder privilege",
    "beauty privilege",
    "lookism",
    "pretty privilege",
    "thin privilege",
    "fat phobia",
    "sizeism",
    "ableism",
    "audism",
    "mentalism",
    "sanism",
    "neurodiversity",
    "neurotypical privilege",
    "allism",
    "cisgenderism",
    "heteronormativity",
    "heterosexism",
    "monosexism",
    "monogamism",
    "amatonormativity",
    "sex-negativity",
    "slut-shaming",
    "prude-shaming",
    "kink-shaming",
    "vanilla-shaming",
    "ace-erasure",
    "bi-erasure",
    "pan-erasure",
    "trans-erasure",
    "nonbinary erasure",
    "genderqueer erasure",
    "agender erasure",
    "aromantic erasure",
    "asexual erasure",
    "demisexual erasure",
    "graysexual erasure",
    "sapiosexual erasure",
    "pansexual erasure",
    "polysexual erasure",
    "omnisexual erasure",
    "multisexual erasure",
    "plurisexual erasure",
    "skoliosexual erasure",
    "androgynosexual erasure",
    "gynosexual erasure",
    "androsexual erasure",
  ]
}